# Generated by Django 5.0.7 on 2024-08-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_income_date_alter_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(),
        ),
    ]
